/*
* Copyright (c) 2020 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/

/*
 ****************************************************************************************
 *
 * @file bsp_ppm_trim_table.c
 *
 * @brief Default (weak) PPM compensation trim table for the RA6W1.
 *
 * This file provides the lab-measured default mapping from a calibrated
 * 7-bit temperature code (TEMP_VALUE_AFTER_PROCESS_CAL, [6:0] of register
 * 0x60D0006C) to a signed XTAL40M_CCTRL delta. The table is consumed by
 * the implementation in bsp_ppm_compensation.c.
 *
 * --- Customer re-characterisation ---
 * Both symbols below are defined with BSP_WEAK_REFERENCE so a customer
 * project may override them by providing a non-weak (strong) definition
 * in a project-owned source file under the project's src/ folder. The
 * linker will prefer the strong definitions over these weak defaults.
 *
 * Workflow:
 *   1. Copy this file into your e2studio project's src/ folder
 *      (anywhere outside ra/fsp/, which is regenerated by FSP).
 *   2. Remove the BSP_WEAK_REFERENCE qualifiers on both symbols.
 *   3. Replace the entries with your own characterisation results.
 *      Rows MUST remain sorted ascending by temp_code.
 *   4. Keep bsp_ppm_trim_table_size in sync with the array length.
 *   5. Rebuild. The linker picks your strong definitions over the
 *      pack-shipped weak defaults.
 *
 * Do not edit this file in place inside the FSP pack tree; FSP's
 * "Generate Project Content" step will overwrite changes there on the
 * next regeneration.
 *
 * --- Offline derivation of cctrl_delta ---
 * The CCTRL slope is -0.7 ppm per LSB. For each ambient temperature,
 * measure the residual frequency error (ppm_meas) at the current trim
 * and pick a ppm_target. Then:
 *
 *     cctrl_delta = round( (ppm_target - ppm_meas) / -0.7 )
 *
 * A positive ppm error (clock running fast) yields a positive delta;
 * a negative ppm error (clock running slow) yields a negative delta.
 *
 ****************************************************************************************
 */

#include <stdint.h>

#include "bsp_api.h"
#include "../all/bsp_common.h"
#include "bsp_ppm_trim_table.h"

/* Lab-measured defaults using the stock reference XTAL.
 * Each delta = round( -ppm_meas / 0.7 ), with ppm_target = 0.
 *
 *   ambient     temp_code   ppm_meas   cctrl_delta
 *   +120 C        21         +27.51       +39
 *   +110 C        26         +14.04       +20
 *   +100 C        32          +3.55        +5
 *    +90 C        37          -3.08        -4
 *    +80 C        43          -7.64       -11
 *    +70 C        49          -9.30       -13
 *    +60 C        54          -8.80       -13
 *    +50 C        61          -6.48        -9
 *    +40 C        65          -4.33        -6
 *    +30 C        71          -1.26        -2
 *    +25 C        74          +0.52        +1
 *    +20 C        77          +2.22        +3
 *    +10 C        81          +5.04        +7
 *      0 C        87          +7.53       +11
 *    -10 C        93          +8.65       +12
 *    -20 C        97          +8.34       +12
 *    -30 C       101          +6.64        +9
 *    -40 C       105          +4.05        +6
 */
BSP_WEAK_REFERENCE
const bsp_ppm_trim_entry_t bsp_ppm_trim_table[] =
{
    /* temp_code, cctrl_delta */
    {21,  +39},
    {26,  +20},
    {32,  +5 },
    {37,  -4 },
    {43,  -11},
    {49,  -13},
    {54,  -13},
    {61,  -9 },
    {65,  -6 },
    {71,  -2 },
    {74,  +1 },
    {77,  +3 },
    {81,  +7 },
    {87,  +11},
    {93,  +12},
    {97,  +12},
    {101, +9 },
    {105, +6 },
};

BSP_WEAK_REFERENCE
const uint32_t bsp_ppm_trim_table_size = FSP_ARRAY_LENGTH(bsp_ppm_trim_table);
