/*
* Copyright (c) 2020 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/

#ifndef RM_ATCMD_W_CORE_ERR_CODE_H
#define RM_ATCMD_W_CORE_ERR_CODE_H

/***********************************************************************************************************************
 * Macro definitions
 **********************************************************************************************************************/

/* ATCMD Error Response Codes */
typedef enum _fsp_err_atcmd_err_code
{
    FSP_ERR_AT_CMD_ERR_UNKNOWN_CMD         = 0x500001, /*< Unknown command */
    FSP_ERR_AT_CMD_ERR_INSUFFICIENT_ARGS   = 0x500002, /*< Insufficient parameter */
    FSP_ERR_AT_CMD_ERR_TOO_MANY_ARGS       = 0x500003, /*< Too many parameters */
    FSP_ERR_AT_CMD_ERR_WRONG_ARGUMENTS     = 0x500004, /*< Wrong parameter value */
    FSP_ERR_AT_CMD_ERR_NOT_SUPPORTED       = 0x500005, /*< Unsupported function */
    FSP_ERR_AT_CMD_ERR_NOT_CONNECTED       = 0x500006, /*< Not connected to an AP or a socket */
    FSP_ERR_AT_CMD_ERR_NO_RESULT           = 0x500007, /*< No result */
    FSP_ERR_AT_CMD_ERR_TOO_LONG_RESULT     = 0x500008, /*< Response buffer overflow */
    FSP_ERR_AT_CMD_ERR_INSUFFICIENT_CONFIG = 0x500009, /*< Function is not configured */
    FSP_ERR_AT_CMD_ERR_TIMEOUT             = 0x50000a, /*< Command timeout */
    FSP_ERR_AT_CMD_ERR_NVR_WRITE           = 0x50000b, /*< NVRAM write failure */
    FSP_ERR_AT_CMD_ERR_RTM_WRITE           = 0x50000c, /*< Retention memory write failure */
    FSP_ERR_AT_CMD_ERR_SYS_BUSY            = 0x50000d, /*< System busy so cannot handle the request */
    FSP_ERR_AT_CMD_ERR_MEM_ALLOC           = 0x50000e, /*< Memory allocation failure */
    FSP_ERR_AT_CMD_ERR_CMD_OK              = 0x50000f, /*< No error */

    FSP_ERR_AT_CMD_ERR_DATA_TX         = 0x500014,     /*< Data Tx failure */
    FSP_ERR_AT_CMD_ERR_IP_ADDRESS      = 0x500016,     /*< IP address get failure */
    FSP_ERR_AT_CMD_ERR_CMD_OK_WO_PRINT = 0x500017,     /*< No error (without Debugging messages) */

    FSP_ERR_AT_CMD_ERR_COMMON_SYS_MODE = 0x500064,     /*< AT-CMD Common function relevant */

    FSP_ERR_AT_CMD_ERR_COMMON_ARG_TYPE       = 0x50006e,
    FSP_ERR_AT_CMD_ERR_COMMON_ARG_RANGE      = 0x50006f,
    FSP_ERR_AT_CMD_ERR_COMMON_ARG_LEN        = 0x500070,
    FSP_ERR_AT_CMD_ERR_COMMON_WRONG_CC       = 0x500071,
    FSP_ERR_AT_CMD_ERR_COMMON_WRONG_MAC_ADDR = 0x500072,

    FSP_ERR_AT_CMD_ERR_SFLASH_READ   = 0x5000aa, /*< AT-CMD FLASH operation relevant */
    FSP_ERR_AT_CMD_ERR_SFLASH_WRITE  = 0x5000ab,
    FSP_ERR_AT_CMD_ERR_SFLASH_ERASE  = 0x5000ac,
    FSP_ERR_AT_CMD_ERR_SFLASH_ACCESS = 0x5000ad,
    FSP_ERR_AT_CMD_ERR_SFLASH_VERIFY = 0x5000ae,
    FSP_ERR_AT_CMD_ERR_SFLASH_INIT   = 0x5000af,

    FSP_ERR_AT_CMD_ERR_NVRAM_READ            = 0x5000b4, /*< AT-CMD NVRAM operation relevant */
    FSP_ERR_AT_CMD_ERR_NVRAM_WRITE           = 0x5000b5,
    FSP_ERR_AT_CMD_ERR_NVRAM_ERASE           = 0x5000b6,
    FSP_ERR_AT_CMD_ERR_NVRAM_DIGIT           = 0x5000b7,
    FSP_ERR_AT_CMD_ERR_NVRAM_SAME_MAC        = 0x5000b8,
    FSP_ERR_AT_CMD_ERR_NVRAM_CANCELED        = 0x5000b9,
    FSP_ERR_AT_CMD_ERR_NVRAM_INVALID         = 0x5000ba,
    FSP_ERR_AT_CMD_ERR_NVRAM_UNKNOWN         = 0x5000bb,
    FSP_ERR_AT_CMD_ERR_NVRAM_NOT_SAVED_VALUE = 0x5000bc,

    FSP_ERR_AT_CMD_ERR_BASIC_ARG_NULL_PTR = 0x5000c8, /*< AT-CMD Basic function relevant */
    FSP_ERR_AT_CMD_ERR_BASIC_ARG_DATE     = 0x5000c9,
    FSP_ERR_AT_CMD_ERR_BASIC_ARG_TIME     = 0x5000ca,
    FSP_ERR_AT_CMD_ERR_BASIC_ARG_TIME_ETC = 0x5000cb,

    FSP_ERR_AT_CMD_ERR_UART_INTERFACE      = 0x5000dc, /*< AT-CMD UART function relevant */
    FSP_ERR_AT_CMD_ERR_UART_BAUDRATE       = 0x5000dd,
    FSP_ERR_AT_CMD_ERR_UART_DATABITS       = 0x5000de,
    FSP_ERR_AT_CMD_ERR_UART_PARITY         = 0x5000df,
    FSP_ERR_AT_CMD_ERR_UART_STOPBIT        = 0x5000e0,
    FSP_ERR_AT_CMD_ERR_UART_FLOWCTRL       = 0x5000e1,
    FSP_ERR_AT_CMD_ERR_UART_BAUDRATE_NV_WR = 0x5000e2,
    FSP_ERR_AT_CMD_ERR_UART_DATABITS_NV_WR = 0x5000e3,
    FSP_ERR_AT_CMD_ERR_UART_PARITY_NV_WR   = 0x5000e4,
    FSP_ERR_AT_CMD_ERR_UART_STOPBIT_NV_WR  = 0x5000e5,
    FSP_ERR_AT_CMD_ERR_UART_FLOWCTRL_NV_WR = 0x5000e6,
    FSP_ERR_AT_CMD_ERR_UART_DRV_OPS        = 0x5000e7,

    FSP_ERR_AT_CMD_ERR_PMGR_UNSUPPORTED_SYS_MODE     = 0x50012c, /*< AT-CMD PMGR function relevant */
    FSP_ERR_AT_CMD_ERR_PMGR_NO_WIFI_CONN             = 0x50012d,
    FSP_ERR_AT_CMD_ERR_PMGR_CONSTR_RETENTION_NOT_SET = 0x50012e,
    FSP_ERR_AT_CMD_ERR_PMGR_DPM_MODE_ENABLED         = 0x50012f,
    FSP_ERR_AT_CMD_ERR_PMGR_DPM_MODE_DISABLED        = 0x500130,
    FSP_ERR_AT_CMD_ERR_PMGR_DPM_ABN_ARG              = 0x500131,
    FSP_ERR_AT_CMD_ERR_PMGR_SLEEP_STARTED            = 0x500132,
    FSP_ERR_AT_CMD_ERR_PMGR_WAKE_SRC_WIFI_NOT_SET    = 0x500133,

    FSP_ERR_AT_CMD_ERR_WIFI_NOT_CONNECTED            = 0x500190, /*< AT-CMD WIFI function relevant */
    FSP_ERR_AT_CMD_ERR_WIFI_RUN_MODE_TYPE            = 0x500191,
    FSP_ERR_AT_CMD_ERR_WIFI_RUN_MODE_RANGE           = 0x500192,
    FSP_ERR_AT_CMD_ERR_WIFI_MAC_ADDR                 = 0x500193,
    FSP_ERR_AT_CMD_ERR_WIFI_WPS_PIN_NUM              = 0x500194,
    FSP_ERR_AT_CMD_ERR_WIFI_CC_WRONG_FREQ            = 0x500195,
    FSP_ERR_AT_CMD_ERR_WIFI_SCAN_UNSUPPORTED         = 0x500196,
    FSP_ERR_AT_CMD_ERR_WIFI_PSCAN_FREQ_RANGE         = 0x500197,
    FSP_ERR_AT_CMD_ERR_WIFI_PSCAN_CMAX_RANGE         = 0x500198,
    FSP_ERR_AT_CMD_ERR_WIFI_PSCAN_CMIN_RANGE         = 0x500199,
    FSP_ERR_AT_CMD_ERR_WIFI_JAP_SSID_NO_VALUE        = 0x50019a,
    FSP_ERR_AT_CMD_ERR_WIFI_JAP_SSID_LEN             = 0x50019b,
    FSP_ERR_AT_CMD_ERR_WIFI_JAP_SECU_ARG_TYPE        = 0x50019c,
    FSP_ERR_AT_CMD_ERR_WIFI_JAP_SECU_ARG_RANGE       = 0x50019d,
    FSP_ERR_AT_CMD_ERR_WIFI_JAP_OPEN_TOO_MANY_ARG    = 0x50019e,
    FSP_ERR_AT_CMD_ERR_WIFI_JAP_OPEN_HIDDEN_TYPE     = 0x50019f,
    FSP_ERR_AT_CMD_ERR_WIFI_JAP_OPEN_HIDDEN_RANGE    = 0x500200,
    FSP_ERR_AT_CMD_ERR_WIFI_JAP_SECU_HIDDEN_TYPE     = 0x500201,
    FSP_ERR_AT_CMD_ERR_WIFI_JAP_SECU_HIDDEN_RANGE    = 0x500202,
    FSP_ERR_AT_CMD_ERR_WIFI_JAP_WEP_IDX_TYPE         = 0x500203,
    FSP_ERR_AT_CMD_ERR_WIFI_JAP_WEP_IDX_RANGE        = 0x500204,
    FSP_ERR_AT_CMD_ERR_WIFI_JAP_WEP_KEY_LEN          = 0x500205,
    FSP_ERR_AT_CMD_ERR_WIFI_JAP_WPA_MODE_TYPE        = 0x500206,
    FSP_ERR_AT_CMD_ERR_WIFI_JAP_WPA_MODE_RANGE       = 0x500207,
    FSP_ERR_AT_CMD_ERR_WIFI_JAP_WPA_KEY_LEN          = 0x500208,
    FSP_ERR_AT_CMD_ERR_WIFI_JAPA_SSID_NO_VALUE       = 0x500209,
    FSP_ERR_AT_CMD_ERR_WIFI_JAPA_SSID_LEN            = 0x50020a,
    FSP_ERR_AT_CMD_ERR_WIFI_JAPA_PSK_LEN             = 0x50020b,
    FSP_ERR_AT_CMD_ERR_WIFI_JAPA_WEP_NOT_SUPPORT     = 0x50020c,
    FSP_ERR_AT_CMD_ERR_WIFI_JAPA_HIDDEN_TYPE         = 0x50020d,
    FSP_ERR_AT_CMD_ERR_WIFI_JAPA_HIDDEN_RANGE        = 0x50020e,
    FSP_ERR_AT_CMD_ERR_WIFI_JAPA_WPA3_MODE_TYPE      = 0x50020f,
    FSP_ERR_AT_CMD_ERR_WIFI_JAPA_WPA3_MODE_RANGE     = 0x500210,
    FSP_ERR_AT_CMD_ERR_WIFI_JAPA_WPA3_HIDDEN_TYPE    = 0x500211,
    FSP_ERR_AT_CMD_ERR_WIFI_JAPA_WPA3_HIDDEN_RANGE   = 0x500212,
    FSP_ERR_AT_CMD_ERR_WIFI_ROAP_ROAM_TYPE           = 0x500213,
    FSP_ERR_AT_CMD_ERR_WIFI_ROAP_ROAM_RANGE          = 0x500214,
    FSP_ERR_AT_CMD_ERR_WIFI_ENTAP_SSID_NO_VALUE      = 0x500215,
    FSP_ERR_AT_CMD_ERR_WIFI_ENTAP_SSID_LEN           = 0x500216,
    FSP_ERR_AT_CMD_ERR_WIFI_ENTAP_AUTH0_UNSUPPORT    = 0x500217,
    FSP_ERR_AT_CMD_ERR_WIFI_ENTAP_ENC0_UNSUPPORT     = 0x500218,
    FSP_ERR_AT_CMD_ERR_WIFI_ENTAP_EAP_PHASE1         = 0x500219,
    FSP_ERR_AT_CMD_ERR_WIFI_ENTAP_EAP_PHASE2         = 0x50021a,
    FSP_ERR_AT_CMD_ERR_WIFI_ENTAP_SECU_MODE          = 0x50021b,
    FSP_ERR_AT_CMD_ERR_WIFI_ENTAP_ENC_MODE           = 0x50021c,
    FSP_ERR_AT_CMD_ERR_WIFI_ENTAP_EAP_MODE           = 0x50021d,
    FSP_ERR_AT_CMD_ERR_WIFI_ENTAP_EAP_ID_NO_VALUE    = 0x50021e,
    FSP_ERR_AT_CMD_ERR_WIFI_ENTAP_EAP_ID_LEN         = 0x50021f,
    FSP_ERR_AT_CMD_ERR_WIFI_ENTAP_EAP_PWD_LEN        = 0x500220,
    FSP_ERR_AT_CMD_ERR_WIFI_SOFTAP_SSID_NO_VALUE     = 0x500221,
    FSP_ERR_AT_CMD_ERR_WIFI_SOFTAP_SECU_MODE         = 0x500222,
    FSP_ERR_AT_CMD_ERR_WIFI_SOFTAP_ENC_MODE          = 0x500223,
    FSP_ERR_AT_CMD_ERR_WIFI_SOFTAP_CH_VALUE_TYPE     = 0x500224,
    FSP_ERR_AT_CMD_ERR_WIFI_SOFTAP_CH_VALUE_RANGE    = 0x500225,
    FSP_ERR_AT_CMD_ERR_WIFI_SOFTAP_OPEN_TOO_MANY_ARG = 0x500226,
    FSP_ERR_AT_CMD_ERR_WIFI_SOFTAP_CH_TX_PWR_VALUE   = 0x500227,
    FSP_ERR_AT_CMD_ERR_WIFI_SOFTAP_WEP_NOT_SUPPORT   = 0x500228,
    FSP_ERR_AT_CMD_ERR_WIFI_SOFTAP_ENC_MODE_TYPE     = 0x500229,
    FSP_ERR_AT_CMD_ERR_WIFI_SOFTAP_ENC_MODE_RANGE    = 0x50022a,
    FSP_ERR_AT_CMD_ERR_WIFI_SOFTAP_PASSKEY_LEN       = 0x50022b,

    FSP_ERR_AT_CMD_ERR_WIFI_ALREADY_CONNECTED       = 0x5001cc, /*< Additional WIFI error code */
    FSP_ERR_AT_CMD_ERR_WIFI_CONCURRENT_NO_PROFILE   = 0x5001cd,
    FSP_ERR_AT_CMD_ERR_WIFI_PSCAN_DURATION          = 0x5001ce,
    FSP_ERR_AT_CMD_ERR_WIFI_JAPA_WPA3_PSK_LEN       = 0x5001cf,
    FSP_ERR_AT_CMD_ERR_WIFI_SOFTAP_OWE_TOO_MANY_ARG = 0x5001d0,
    FSP_ERR_AT_CMD_ERR_WIFI_SOFTAP_SSID_LEN         = 0x5001d1,
    FSP_ERR_AT_CMD_ERR_WIFI_SCAN_BAND_TYPE          = 0x5001d2,
    FSP_ERR_AT_CMD_ERR_WIFI_SCAN_BAND_RANGE         = 0x5001d3,
    FSP_ERR_AT_CMD_ERR_WIFI_ENTAP_WPA_HIDDEN_TYPE   = 0x5001d4,
    FSP_ERR_AT_CMD_ERR_WIFI_ENTAP_WPA_HIDDEN_RANGE  = 0x5001d5,
    FSP_ERR_AT_CMD_ERR_WIFI_JAPMK_PMK_FMT           = 0x5001d6,

    FSP_ERR_AT_CMD_ERR_WIFI_P2P_CONN_WPS_TYPE      = 0x5001e1, /*< AT-CMD WiFI-Wi-Fi Direct,p2p_connect<MAC> */
    FSP_ERR_AT_CMD_ERR_WIFI_P2P_UNSUPPORT_WPS_TYPE = 0x5001e2,
    FSP_ERR_AT_CMD_ERR_WIFI_P2P_CONN_JOIN_TYPE     = 0x5001e3,
    FSP_ERR_AT_CMD_ERR_WIFI_P2P_CONN_JOIN_RANGE    = 0x5001e4,
    FSP_ERR_AT_CMD_ERR_WIFI_P2P_LISTEN_CH_TYPE     = 0x5001e5,
    FSP_ERR_AT_CMD_ERR_WIFI_P2P_LISTEN_CH_RANGE    = 0x5001e6,
    FSP_ERR_AT_CMD_ERR_WIFI_P2P_OPERATION_CH       = 0x5001e7,
    FSP_ERR_AT_CMD_ERR_WIFI_P2P_OPERATION_CH_RANGE = 0x5001e8,
    FSP_ERR_AT_CMD_ERR_WIFI_P2P_GO_INTENT          = 0x5001e9,
    FSP_ERR_AT_CMD_ERR_WIFI_P2P_GO_INTENT_RANGE    = 0x5001ea,
    FSP_ERR_AT_CMD_ERR_WIFI_P2P_FIND_TIMEOUT_TYPE  = 0x5001eb,
    FSP_ERR_AT_CMD_ERR_WIFI_P2P_FIND_TIMEOUT_RANGE = 0x5001ec,
    FSP_ERR_AT_CMD_ERR_WIFI_P2P_FIND_TIMEOUT       = 0x5001ed,

    FSP_ERR_AT_CMD_ERR_WIFI_CLI_STATUS             = 0x5001f4, /*< AT-CMD WIFI CLI operation related-common */
    FSP_ERR_AT_CMD_ERR_WIFI_CLI_SET_NETWORK        = 0x5001f5,
    FSP_ERR_AT_CMD_ERR_WIFI_CLI_SET_NETWORK_HIDDEN = 0x5001f6,
    FSP_ERR_AT_CMD_ERR_WIFI_CLI_SELECT_NETWORK     = 0x5001f7,
    FSP_ERR_AT_CMD_ERR_WIFI_CLI_SAVE_CONF          = 0x5001f8,
    FSP_ERR_AT_CMD_ERR_WIFI_CLI_SAVE_CONF_HIDDEN   = 0x5001f9,
    FSP_ERR_AT_CMD_ERR_WIFI_CLI_DISCONNECT         = 0x5001fa,
    FSP_ERR_AT_CMD_ERR_WIFI_CLI_DEAUTHENTICATE     = 0x5001fb, /*< cli deauthenticate <MAC> */
    FSP_ERR_AT_CMD_ERR_WIFI_CLI_DISASSOCIATE       = 0x5001fc, /*< cli disassociate <MAC> */

    FSP_ERR_AT_CMD_ERR_WIFI_CLI_WPS_PBC_ANY    = 0x5001fe,     /*< AT-CMD WIFI CLI operation relevant */
    FSP_ERR_AT_CMD_ERR_WIFI_CLI_WPS_PIN_GET    = 0x5001ff,
    FSP_ERR_AT_CMD_ERR_WIFI_CLI_WPS_PIN_ANY    = 0x500200,
    FSP_ERR_AT_CMD_ERR_WIFI_CLI_WPS_PIN_NUM    = 0x500201,
    FSP_ERR_AT_CMD_ERR_WIFI_CLI_WPS_CANCEL     = 0x500202,
    FSP_ERR_AT_CMD_ERR_WIFI_CLI_COUNTRY        = 0x500203,
    FSP_ERR_AT_CMD_ERR_WIFI_CLI_PSCAN_CH_TL    = 0x500204,
    FSP_ERR_AT_CMD_ERR_WIFI_CLI_PSCAN_STOP     = 0x500205,
    FSP_ERR_AT_CMD_ERR_WIFI_CLI_PSCAN_CMAX_GET = 0x500206,
    FSP_ERR_AT_CMD_ERR_WIFI_CLI_PSCAN_CMAX_SET = 0x500207,
    FSP_ERR_AT_CMD_ERR_WIFI_CLI_PSCAN_CMIN_GET = 0x500208,
    FSP_ERR_AT_CMD_ERR_WIFI_CLI_PSCAN_CMIN_SET = 0x500209,

    FSP_ERR_AT_CMD_ERR_WIFI_CLI_SOFTAP_START   = 0x50020a,      /*< cli ap start */
    FSP_ERR_AT_CMD_ERR_WIFI_CLI_SOFTAP_STOP    = 0x50020b,      /*< cli ap stop */
    FSP_ERR_AT_CMD_ERR_WIFI_CLI_SOFTAP_RESTART = 0x50020c,      /*< cli ap restart */

    FSP_ERR_AT_CMD_ERR_WIFI_CLI_P2P_FIND            = 0x500212, /*< cli p2p_find */
    FSP_ERR_AT_CMD_ERR_WIFI_CLI_P2P_FIND_STOP       = 0x500213, /*< cli p2p_stop_find */
    FSP_ERR_AT_CMD_ERR_WIFI_CLI_P2P_JOIN            = 0x500214, /*< cli p2p_connect pbc <join> */
    FSP_ERR_AT_CMD_ERR_WIFI_CLI_P2P_GRP_REMOVE      = 0x500215, /*< cli p2p_group_remove */
    FSP_ERR_AT_CMD_ERR_WIFI_CLI_P2P_PEER_INFO       = 0x500216, /*< cli p2p_peers */
    FSP_ERR_AT_CMD_ERR_WIFI_CLI_P2P_LISTEN_CH       = 0x500217,
    FSP_ERR_AT_CMD_ERR_WIFI_CLI_P2P_LISTEN_CH_RANGE = 0x500218,

    FSP_ERR_AT_CMD_ERR_NW_NET_IF_NOT_INITIALIZE = 0x500258,     /*< AT-CMD Network function relevant */
    FSP_ERR_AT_CMD_ERR_NW_NET_IF_IS_DOWN        = 0x500259,
    FSP_ERR_AT_CMD_ERR_NW_IP_IFACE_TYPE         = 0x50025a,
    FSP_ERR_AT_CMD_ERR_NW_IP_IFACE_RANGE        = 0x50025b,
    FSP_ERR_AT_CMD_ERR_NW_IP_ADDR_CLASS         = 0x50025c,
    FSP_ERR_AT_CMD_ERR_NW_IP_INVALID_ADDR       = 0x50025d,
    FSP_ERR_AT_CMD_ERR_NW_IP_NETMASK            = 0x50025e,
    FSP_ERR_AT_CMD_ERR_NW_IP_GATEWAY            = 0x50025f,
    FSP_ERR_AT_CMD_ERR_NW_DNS_A_QUERY_FAIL      = 0x500260,
    FSP_ERR_AT_CMD_ERR_NW_PING_IFACE_ARG_TYPE   = 0x500261,
    FSP_ERR_AT_CMD_ERR_NW_PING_IFACE_ARG_RANGE  = 0x500262,
    FSP_ERR_AT_CMD_ERR_NW_PING_DST_ADDR         = 0x500263,
    FSP_ERR_AT_CMD_ERR_NW_PING_TX_COUNT         = 0x500264,

    FSP_ERR_AT_CMD_ERR_NW_DHCPC_START_FAIL    = 0x500265,         /*< For DHCP-Client relevant */
    FSP_ERR_AT_CMD_ERR_NW_DHCPC_HOSTNAME_LEN  = 0x500266,
    FSP_ERR_AT_CMD_ERR_NW_DHCPC_HOSTNAME_TYPE = 0x500267,

    FSP_ERR_AT_CMD_ERR_NW_DHCPS_START_ADDR_NOT_EXIST  = 0x500268, /*< For DHCP-Server relevant */
    FSP_ERR_AT_CMD_ERR_NW_DHCPS_END_ADDR_NOT_EXIST    = 0x500269,
    FSP_ERR_AT_CMD_ERR_NW_DHCPS_WRONG_START_IP_CLASS  = 0x50026a,
    FSP_ERR_AT_CMD_ERR_NW_DHCPS_WRONG_END_IP_CLASS    = 0x50026b,
    FSP_ERR_AT_CMD_ERR_NW_DHCPS_IPADDR_RANGE_MISMATCH = 0x50026c,
    FSP_ERR_AT_CMD_ERR_NW_DHCPS_IPADDR_RANGE_OVERFLOW = 0x50026d,
    FSP_ERR_AT_CMD_ERR_NW_DHCPS_NO_CONNECTED_CLIENT   = 0x50026e,
    FSP_ERR_AT_CMD_ERR_NW_DHCPS_RUN_FLAG_TYPE         = 0x50026f,
    FSP_ERR_AT_CMD_ERR_NW_DHCPS_RUN_FLAG_VAL          = 0x500270,
    FSP_ERR_AT_CMD_ERR_NW_DHCPS_LEASE_TIME_TYPE       = 0x500271,
    FSP_ERR_AT_CMD_ERR_NW_DHCPS_LEASE_TIME_RANGE      = 0x500272,

    FSP_ERR_AT_CMD_ERR_NW_DHCPS_DNS_SVR_ADDR_NOT_EXIST = 0x500273,
    FSP_ERR_AT_CMD_ERR_NW_DHCPS_DNS_SVR_ADDR_CLASS     = 0x500274,

    FSP_ERR_AT_CMD_ERR_NW_SNTP_NOT_SUPPORTED = 0x500275, /*< For SNTP Client relevant */
    FSP_ERR_AT_CMD_ERR_NW_SNTP_FLAG_TYPE     = 0x500276,
    FSP_ERR_AT_CMD_ERR_NW_SNTP_FLAG_VAL      = 0x500277,
    FSP_ERR_AT_CMD_ERR_NW_SNTP_PERIOD_TYPE   = 0x500278,
    FSP_ERR_AT_CMD_ERR_NW_SNTP_PERIOD_RANGE  = 0x500279,

    FSP_ERR_AT_CMD_ERR_NW_MQTT_NOT_CONNECTED     = 0x50027a, /*< For MQTT-Client relevant */
    FSP_ERR_AT_CMD_ERR_NW_MQTT_NEED_TO_STOP      = 0x50027b,
    FSP_ERR_AT_CMD_ERR_NW_MQTT_UNKNOWN_OP_ID     = 0x50027c,
    FSP_ERR_AT_CMD_ERR_NW_MQTT_CLIENT_TASK_START = 0x50027d,

    FSP_ERR_AT_CMD_ERR_NW_MQTT_BROKER_NAME_NOT_FOUND = 0x50027e, /*< MQTT Broker setting relevant */
    FSP_ERR_AT_CMD_ERR_NW_MQTT_BROKER_PORT_NUM_TYPE  = 0x50027f,
    FSP_ERR_AT_CMD_ERR_NW_MQTT_BROKER_PORT_NUM_RANGE = 0x500280,
    FSP_ERR_AT_CMD_ERR_NW_MQTT_BROKER_NAME_LEN       = 0x500281,

    FSP_ERR_AT_CMD_ERR_NW_MQTT_TLS_TYPE                 = 0x500282, /*< MQTT TLS setting relevant */
    FSP_ERR_AT_CMD_ERR_NW_MQTT_TLS_RANGE                = 0x500283,
    FSP_ERR_AT_CMD_ERR_NW_MQTT_TLS_ALPN_NOT_EXIST       = 0x500284,
    FSP_ERR_AT_CMD_ERR_NW_MQTT_TLS_ALPN_COUNT_TYPE      = 0x500285,
    FSP_ERR_AT_CMD_ERR_NW_MQTT_TLS_ALPN_COUNT_RANGE     = 0x500286,
    FSP_ERR_AT_CMD_ERR_NW_MQTT_TLS_ALPN_NAME_LEN        = 0x500287,
    FSP_ERR_AT_CMD_ERR_NW_MQTT_TLS_SNI_NOT_EXIST        = 0x500288,
    FSP_ERR_AT_CMD_ERR_NW_MQTT_TLS_SNI_LEN              = 0x500289,
    FSP_ERR_AT_CMD_ERR_NW_MQTT_TLS_CSUITE_NUM_NOT_EXIST = 0x50028a,
    FSP_ERR_AT_CMD_ERR_NW_MQTT_TLS_CSUITE_NOT_EXIST     = 0x50028b,
    FSP_ERR_AT_CMD_ERR_NW_MQTT_TLS_CSUITE_NUM_NVRAM_WR  = 0x50028c,
    FSP_ERR_AT_CMD_ERR_NW_MQTT_TLS_CSUITE_NVRAM_WR      = 0x50028d,

    FSP_ERR_AT_CMD_ERR_NW_MQTT_SUBS_TOPIC_NOT_EXIST     = 0x50028e, /*< MQTT Subscribe-topic relevant */
    FSP_ERR_AT_CMD_ERR_NW_MQTT_SUBS_TOPIC_NUM_TYPE      = 0x50028f,
    FSP_ERR_AT_CMD_ERR_NW_MQTT_SUBS_TOPIC_NUM_RANGE     = 0x500290,
    FSP_ERR_AT_CMD_ERR_NW_MQTT_SUBS_TOPIC_LEN           = 0x500291,
    FSP_ERR_AT_CMD_ERR_NW_MQTT_SUBS_TOPIC_DUP           = 0x500292,
    FSP_ERR_AT_CMD_ERR_NW_MQTT_SUBS_TOPIC_NUM_NVRAM_WR  = 0x500293,
    FSP_ERR_AT_CMD_ERR_NW_MQTT_SUBS_TOPIC_NUM_OVERFLOW  = 0x500294,
    FSP_ERR_AT_CMD_ERR_NW_MQTT_SUBS_TOPIC_ALREADY_EXIST = 0x500295,

    FSP_ERR_AT_CMD_ERR_NW_MQTT_PUB_TOPIC_NOT_EXIST = 0x500296,    /*< MQTT Publisher-topic relevant */
    FSP_ERR_AT_CMD_ERR_NW_MQTT_PUB_TOPIC_LEN       = 0x500297,

    FSP_ERR_AT_CMD_ERR_NW_MQTT_WILL_TOPIC_NOT_EXIST   = 0x500298, /*< MQTT Will message relevant */
    FSP_ERR_AT_CMD_ERR_NW_MQTT_WILL_MESSAGE_NOT_EXIST = 0x500299,
    FSP_ERR_AT_CMD_ERR_NW_MQTT_WILL_TOPIC_LEN         = 0x50029a,
    FSP_ERR_AT_CMD_ERR_NW_MQTT_WILL_MESSAGE_LEN       = 0x50029b,
    FSP_ERR_AT_CMD_ERR_NW_MQTT_WILL_QOS_TYPE          = 0x50029c,
    FSP_ERR_AT_CMD_ERR_NW_MQTT_WILL_QOS_RANGE         = 0x50029d,

    FSP_ERR_AT_CMD_ERR_NW_MQTT_PROTOCOL           = 0x50029e, /*< MQTT Common error */
    FSP_ERR_AT_CMD_ERR_NW_MQTT_PING_PERIOD_TYPE   = 0x50029f,
    FSP_ERR_AT_CMD_ERR_NW_MQTT_PING_PERIOD_RANGE  = 0x5002a0,
    FSP_ERR_AT_CMD_ERR_NW_MQTT_USERNAME_NOT_EXIST = 0x5002a1,
    FSP_ERR_AT_CMD_ERR_NW_MQTT_USERNAME_LEN       = 0x5002a2,
    FSP_ERR_AT_CMD_ERR_NW_MQTT_PASSWORD_LEN       = 0x5002a3,
    FSP_ERR_AT_CMD_ERR_NW_MQTT_PUB_MESSAGE_LEN    = 0x5002a4,
    FSP_ERR_AT_CMD_ERR_NW_MQTT_PUB_TX_IN_PROGRESS = 0x5002a5,

    FSP_ERR_AT_CMD_ERR_NW_HTS_TASK_CREATE_FAIL  = 0x5002a8, /*< For HTTP(s) relevant */
    FSP_ERR_AT_CMD_ERR_NW_HTSS_TASK_CREATE_FAIL = 0x5002a9,
    FSP_ERR_AT_CMD_ERR_NW_HTC_TASK_CREATE_FAIL  = 0x5002aa,
    FSP_ERR_AT_CMD_ERR_NW_HTC_ALPN_CNT_TYPE     = 0x5002ab,
    FSP_ERR_AT_CMD_ERR_NW_HTC_ALPN_CNT_RANGE    = 0x5002ac,
    FSP_ERR_AT_CMD_ERR_NW_HTC_ALPN1_STR_LEN     = 0x5002ad,
    FSP_ERR_AT_CMD_ERR_NW_HTC_ALPN2_STR_LEN     = 0x5002ae,
    FSP_ERR_AT_CMD_ERR_NW_HTC_ALPN3_STR_LEN     = 0x5002af,
    FSP_ERR_AT_CMD_ERR_NW_HTC_SNI_LEN           = 0x5002b0,

    FSP_ERR_AT_CMD_ERR_NW_WSC_URL_STR_LEN           = 0x5002b1, /*< For Web-Socket client relevant */
    FSP_ERR_AT_CMD_ERR_NW_WSC_INVALID_URL           = 0x5002b2,
    FSP_ERR_AT_CMD_ERR_NW_WSC_TASK_ALREADY_EXIST    = 0x5002b3,
    FSP_ERR_AT_CMD_ERR_NW_WSC_CB_FUNC_DOES_NO_EXIST = 0x5002b4,
    FSP_ERR_AT_CMD_ERR_NW_WSC_INVALID_STATE         = 0x5002b5,
    FSP_ERR_AT_CMD_ERR_NW_WSC_TASK_CREATE_FAIL      = 0x5002b6,
    FSP_ERR_AT_CMD_ERR_NW_WSC_CLOSE_FAIL            = 0x5002b7,
    FSP_ERR_AT_CMD_ERR_NW_WSC_SESS_NOT_CONNECTED    = 0x5002b8,
    FSP_ERR_AT_CMD_ERR_NW_WSC_UNKNOW_CMD            = 0x5002b9,
    FSP_ERR_AT_CMD_ERR_NW_WSC_INVALID_VALUE         = 0x5002ba,

    FSP_ERR_AT_CMD_ERR_NW_OTA_WRONG_FW_TYPE           = 0x5002bc, /*< For OTA update relevant */
    FSP_ERR_AT_CMD_ERR_NW_OTA_DOWN_OK_AND_WAIT_RENEW  = 0x5002bd,
    FSP_ERR_AT_CMD_ERR_NW_OTA_FLASH_READ_SIZE_TYPE    = 0x5002be,
    FSP_ERR_AT_CMD_ERR_NW_OTA_FLASH_COPY_SIZE_TYPE    = 0x5002bf,
    FSP_ERR_AT_CMD_ERR_NW_OTA_FLASH_ERASE_SIZE_TYPE   = 0x5002c0,
    FSP_ERR_AT_CMD_ERR_NW_OTA_BY_MCU_INIT             = 0x5002c1,
    FSP_ERR_AT_CMD_ERR_NW_OTA_SET_TLS_AUTH_MODE_NVRAM = 0x5002c2,
    FSP_ERR_AT_CMD_ERR_NW_OTA_SET_MCU_FW_NAME         = 0x5002c3,

    FSP_ERR_AT_CMD_ERR_NW_MODULE_NOT_RESERVED = 0x5002d7,           /*< For Certificates relevant */

    FSP_ERR_AT_CMD_ERR_TCP_SERVER_LOCAL_PORT_TYPE       = 0x5002da, /*< AT-CMD transport function relevant */
    FSP_ERR_AT_CMD_ERR_TCP_SERVER_MAX_PEER_TYPE         = 0x5002db,
    FSP_ERR_AT_CMD_ERR_TCP_SERVER_TASK_CREATE           = 0x5002dc,
    FSP_ERR_AT_CMD_ERR_TCP_CLIENT_SVR_PORT_TYPE         = 0x5002de,
    FSP_ERR_AT_CMD_ERR_TCP_CLIENT_LOCAL_PORT_TYPE       = 0x5002df,
    FSP_ERR_AT_CMD_ERR_TCP_CLIENT_MAX_PEER_TYPE         = 0x5002e0,
    FSP_ERR_AT_CMD_ERR_TCP_CLIENT_TASK_CREATE           = 0x5002e1,
    FSP_ERR_AT_CMD_ERR_UDP_SESS_LOCAL_PORT_TYPE         = 0x5002e2,
    FSP_ERR_AT_CMD_ERR_UDP_SESS_LOCAL_PORT_RANGE        = 0x5002e3,
    FSP_ERR_AT_CMD_ERR_UDP_SESS_TASK_CREATE             = 0x5002e4,
    FSP_ERR_AT_CMD_ERR_UDP_CID2_SESS_NOT_EXIST          = 0x5002e5,
    FSP_ERR_AT_CMD_ERR_UDP_CID2_SESS_ALREADY_EXIST      = 0x5002e6,
    FSP_ERR_AT_CMD_ERR_UDP_CID2_SESS_INFO               = 0x5002e7,
    FSP_ERR_AT_CMD_ERR_UDP_CID2_REMOTE_PORT_TYPE        = 0x5002e8,
    FSP_ERR_AT_CMD_ERR_NO_CONNECTED_SESSION_EXIST       = 0x5002e9,
    FSP_ERR_AT_CMD_ERR_NO_FOUND_REQ_CID_SESSION         = 0x5002ea,
    FSP_ERR_AT_CMD_ERR_CONTEXT_CID_TYPE                 = 0x5002eb,
    FSP_ERR_AT_CMD_ERR_CONTEXT_DELETE                   = 0x5002ec,
    FSP_ERR_AT_CMD_ERR_CONTEXT_TYPE_IS_NOT_TCP_SVR      = 0x5002ed,
    FSP_ERR_AT_CMD_ERR_CONTEXT_INVALID_SESS_TYPE        = 0x5002ee,
    FSP_ERR_AT_CMD_ERR_TRTRM_CID_TYPE                   = 0x5002ef,
    FSP_ERR_AT_CMD_ERR_TRTRM_REMOTE_PORT_NUM_TYPE       = 0x5002f0,
    FSP_ERR_AT_CMD_ERR_TRTRM_TCP_SVR_REMOTE_SESS_DISCON = 0x5002f1,
    FSP_ERR_AT_CMD_ERR_TCP_SERVER_TERMINATE             = 0x5002f2,
    FSP_ERR_AT_CMD_ERR_TCP_CLIENT_TERMINATE             = 0x5002f3,
    FSP_ERR_AT_CMD_ERR_UDP_SESSION_TERMINATE            = 0x5002f4,
    FSP_ERR_AT_CMD_ERR_MULTI_SESSION_CID_TERMINATE      = 0x5002f5,
    FSP_ERR_AT_CMD_ERR_NO_SESSION_TO_SAVE_NVRAM         = 0x5002f6,
    FSP_ERR_AT_CMD_ERR_UDP_SESS_CONNECT                 = 0x5002f7,

    FSP_ERR_AT_CMD_ERR_SSL_ROLE_NOT_SUPPORT      = 0x5002f8, /*< AT-CMD SSL/TLS function relevant */
    FSP_ERR_AT_CMD_ERR_SSL_CONF_CID_TYPE         = 0x5002f9,
    FSP_ERR_AT_CMD_ERR_SSL_CONTEXT_NOT_FOUND     = 0x5002fa,
    FSP_ERR_AT_CMD_ERR_SSL_CONTEXT_ALREADY_EXIST = 0x5002fb,
    FSP_ERR_AT_CMD_ERR_SSL_CONF_ID_NOT_SUPPORTED = 0x5002fc,
    FSP_ERR_AT_CMD_ERR_SSL_SAVE_CLR_ALL_NV       = 0x5002fd,
    FSP_ERR_AT_CMD_ERR_SSL_SAVE_FAIL_NV          = 0x5002fe,

    FSP_ERR_AT_CMD_ERR_SSL_CONF_ID_TYPE             = 0x5002ff, /*< AT-CMD SSL Configuration relevant */
    FSP_ERR_AT_CMD_ERR_SSL_CONF_ID_RANGE            = 0x500300,
    FSP_ERR_AT_CMD_ERR_SSL_CONF_CID_CA_CERT_NO_NAME = 0x500301,
    FSP_ERR_AT_CMD_ERR_SSL_CONF_CID_CERT_NO_CERT    = 0x500302,
    FSP_ERR_AT_CMD_ERR_SSL_CONF_CID_SNI             = 0x500303,
    FSP_ERR_AT_CMD_ERR_SSL_CONF_CID_SVR_VALID_TYPE  = 0x500304,
    FSP_ERR_AT_CMD_ERR_SSL_CONF_CID_SVR_VALID_RANGE = 0x500305,
    FSP_ERR_AT_CMD_ERR_SSL_CONF_CID_RX_BUF_LEN      = 0x500306,
    FSP_ERR_AT_CMD_ERR_SSL_CONF_CID_TX_BUF_LEN      = 0x500307,
    FSP_ERR_AT_CMD_ERR_SSL_CONN_CID_TYPE            = 0x500308,
    FSP_ERR_AT_CMD_ERR_SSL_CONN_ALREADY_CONNECTED   = 0x500309,
    FSP_ERR_AT_CMD_ERR_SSL_CONN_PORT_NUM_TYPE       = 0x50030a,
    FSP_ERR_AT_CMD_ERR_SSL_CONN_UNKNOWN_HOSTNAME    = 0x50030b,
    FSP_ERR_AT_CMD_ERR_SSL_CONN_CFG_SETUP_FAIL      = 0x50030c,
    FSP_ERR_AT_CMD_ERR_SSL_CONN_TLS_CLINET_RUN_FAIL = 0x50030d,

    FSP_ERR_AT_CMD_ERR_SSL_CERT_TYPE                    = 0x50030e, /*< AT-CMD SSL Certificate relevant */
    FSP_ERR_AT_CMD_ERR_SSL_CERT_RANGE                   = 0x50030f,
    FSP_ERR_AT_CMD_ERR_SSL_CERT_STO_SEQ_TYPE            = 0x500310,
    FSP_ERR_AT_CMD_ERR_SSL_CERT_STO_SEQ_RANGE           = 0x500311,
    FSP_ERR_AT_CMD_ERR_SSL_CERT_STO_FORMAT_TYPE         = 0x500312,
    FSP_ERR_AT_CMD_ERR_SSL_CERT_STO_FORMAT_RANGE        = 0x500313,
    FSP_ERR_AT_CMD_ERR_SSL_CERT_STO_ALREADY_EXIST       = 0x500314,
    FSP_ERR_AT_CMD_ERR_SSL_CERT_STO_NO_SPACE            = 0x500315,
    FSP_ERR_AT_CMD_ERR_SSL_CERT_DEL_LIST_NOT_FOUND      = 0x500316,
    FSP_ERR_AT_CMD_ERR_SSL_CERT_MODULE                  = 0x500317,
    FSP_ERR_AT_CMD_ERR_SSL_CERT_FORMAT                  = 0x500318,
    FSP_ERR_AT_CMD_ERR_SSL_CERT_LENGTH                  = 0x500319,
    FSP_ERR_AT_CMD_ERR_SSL_CERT_FLASH_ADDR              = 0x50031a,
    FSP_ERR_AT_CMD_ERR_SSL_CERT_EMPTY_CERT              = 0x50031b,
    FSP_ERR_AT_CMD_ERR_SSL_CERT_INTERNAL                = 0x50031c,
    FSP_ERR_AT_CMD_ERR_SSL_SESS_TASK_CREATE             = 0x50031d,
    FSP_ERR_AT_CMD_ERR_SSL_CONF_CID_CA_CERT_NO_ZERO_SEQ = 0x50031e,
    FSP_ERR_AT_CMD_ERR_SSL_CONF_CID_CERT_NO_KEY         = 0x50031f,
    FSP_ERR_AT_CMD_ERR_SSL_CERT_ERR_OK                  = 0x500320,
    FSP_ERR_AT_CMD_ERR_SSL_CERT_ERR_NOK                 = 0x500321,
    FSP_ERR_AT_CMD_ERR_SSL_CERT_ERR_INVALID_PARAMS      = 0x500322,
    FSP_ERR_AT_CMD_ERR_SSL_CERT_ERR_FOPEN_FAILED        = 0x500323,
    FSP_ERR_AT_CMD_ERR_SSL_CERT_ERR_MEM_FAILED          = 0x500324,

    FSP_ERR_AT_CMD_ERR_SECURE_RESYNC_REQ = 0x50032a, /*< AT-CMD Secure Channel relevant */

    FSP_ERR_AT_CMD_ERR_RESERVED_XXX = 0x500330,      /*< Reserved error-code */

    FSP_ERR_AT_CMD_ERR_BLE_XXX = 0x500370,           /*< AT-CMD BLE function */

    FSP_ERR_AT_CMD_ERR_PROV_XXX = 0x50037a,          /*< AT-CMD Provision function */

    FSP_ERR_AT_CMD_ERR_RF_XXX = 0x500384,            /*< AT-CMD RF function */

    FSP_ERR_AT_CMD_ERR_PERI_XXX = 0x5003b6,          /*< AT-CMD Peripheral function */

    FSP_ERR_AT_CMD_ERR_UNKNOWN = 0x5003e7            /*< Unknown error */
} fsp_err_atcmd_err_code;

#endif
